apiVersion: v1
binaryData:
  sha256-7c2001c24aa550aa228cd2d0fc0b5d9ac6656cd4267cd7c156ec758d0687758e-1: owGbwMvMwMEoOU9/4l9n2UDG0wf6khgyjc48q1ZKLsosyUxOzFGyUqhWysxNTE8Fs1Lyk7NTi3RzE/My01KLS3RTMtOBFFBKqTgj0cjUzMo82cjAwDDZyCQx0dTUIDHRyMgiOcUoxSAt2SDJNMUyMdnMzNQsOcXEyMw8OcU82dDULDXZ3NQixcDMwhxIpyrV6igolVQWgKxTSizJz81MVkjOzytJzMxLLVIozkzPSywpLUpVAqrKTEnNK8ksqUR2WFFqWmpRal4yWHthaWKlXma+fn5Bal5xRmZaCVA6JzWxOFU3JbVMPz+5AMa3MtEztNQzMtStsDCLNzNRqgU5Ir+gJDM/DxoCyUWpQMcUgUwNSk1R8EgsUfAHmhoMMlUhGOiqzLx0BcfSkox8YLhVKhjoGegZAo3pZJJhYWDkYGBjZQIFKwMXpwAssPuaBBj6Tda1Hr673iNC3by40ozx2Xf552ui5CNiv3emzrs4r2Na7s7yjo9bo9+t+OfaW7WQRXei3Caxb+nsCZzNn6Y+CJ9mwO/Un3BY97n6rqifyZOE7U7zz5vMwK/5/v7Wj27vPH/PLap5YCri1XJo+WbZiIANuh2HrrS2JbW/t/l5z3v3wwusnEIquSoHbsn93iCU3vVcdNLZ0Cehd557fOF1T3hZUqS9YL5JZohy7W2TviM2NZUumfmF88N0VSoOHVcITY6t0Fm9Xc0sqTDCin9n2lppu1v51cGdfcujztqu8ygSFWblq+jfaXz01YUDeQLzMlrf3VHjKzh/9YLCqqLU4q+Rbz657Ss7ZDN5y5RlPnFMXvq7Du45vyt1+Xfdbvlrj9vYWfmk5tgYrpty+8O9W6HP5rTYyk16dmfzg8Q+Jp8WsSsfH0hMmbhN9OIUly+zOyr2SB7pWCLy27Jh08S1Hwz+TqpVYTk6rW72GgajRy0HFNsfSBVz2ZoKdJ7aNnultdnJxoOnots/X7oqo7E3zPxPz96gtc+3OfIennbj5dQDoqJqF+qOnp/adUpZa7Jo6cEdbSsr9nluaLD60ZSxIjR2S7h1/+KApfY/PUW3n/jbVxQftfzGPvHMfiZn7evv/7/Y7K6ptPji+nfTT9fM2BzodLvyxvxVSs7ap+RlwgOmX3N8/kl9TlX0n7Aybu8md7XakzrlcRPEZ+gDAA==
kind: ConfigMap
metadata:
  annotations:
    createdAt: Tuesday, 20-Jan-26 22:51:36 UTC
    createdBy: oc-mirror v2
    oc-mirror_version: 4.20.0-202510221121.p2.gb51b46d.assembly.stream.el9-b51b46d
  labels:
    release.openshift.io/verification-signatures: ""
  name: mirrored-release-signatures
  namespace: openshift-config-managed
